const fs = require("fs");
const content = [
'import Link from "next/link";',
'import { redirect } from "next/navigation";',
'import { createServerSupabase } from "@/lib/supabase/server";',
'',
'export const dynamic = "force-dynamic";',
'',
'type FriendActivity = {',
'  id: string;',
'  type: "going" | "interested" | "review";',
'  user_id: string;',
'  user_name: string;',
'  user_username: string | null;',
'  created_at: string;',
'  event_id: string | null;',
'  event_title: string | null;',
'  event_date: string | null;',
'  event_image: string | null;',
'  rating?: number;',
'  comment?: string | null;',
'};',
'',
'function formatDate(v: string | null) {',
'  if (!v) return "TBC";',
'  return new Date(v).toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short" });',
'}',
'',
'export default async function FeedPage() {',
'  const supabase = await createServerSupabase();',
'  const { data: { user } } = await supabase.auth.getUser();',
'  if (!user) redirect("/login");',
'',
'  const { data: friendships } = await supabase',
'    .from("friendships")',
'    .select("user_id, friend_id")',
'    .eq("status", "accepted")',
'    .or("user_id.eq." + user.id + ",friend_id.eq." + user.id);',
'',
'  const friendIds = (friendships || []).map((f) =>',
'    f.user_id === user.id ? f.friend_id : f.user_id',
'  );',
'',
'  const activities: FriendActivity[] = [];',
'',
'  if (friendIds.length > 0) {',
'    // Interest activity',
'    const { data: interestRows } = await supabase',
'      .from("event_interest")',
'      .select("id, user_id, event_id, status, created_at")',
'      .in("user_id", friendIds)',
'      .order("created_at", { ascending: false })',
'      .limit(50);',
'',
'    const eventIds = [...new Set((interestRows || []).map((r) => r.event_id))];',
'    const userIds = [...new Set([...friendIds, ...(interestRows || []).map((r) => r.user_id)])];',
'',
'    const { data: events } = eventIds.length',
'      ? await supabase.from("events").select("id, title, start_date, hero_image").in("id", eventIds)',
'      : { data: [] };',
'    const { data: profiles } = await supabase',
'      .from("profiles")',
'      .select("id, full_name, username")',
'      .in("id", friendIds);',
'',
'    const eventById: Record<string, { title: string; start_date: string | null; hero_image: string | null }> = {};',
'    for (const ev of events || []) {',
'      eventById[ev.id] = { title: ev.title, start_date: ev.start_date, hero_image: ev.hero_image };',
'    }',
'    const profileById: Record<string, { name: string; username: string | null }> = {};',
'    for (const p of profiles || []) {',
'      profileById[p.id] = { name: p.full_name || p.username || "Someone", username: p.username };',
'    }',
'',
'    for (const row of interestRows || []) {',
'      if (row.status !== "going" && row.status !== "interested") continue;',
'      const ev = eventById[row.event_id];',
'      const pr = profileById[row.user_id];',
'      if (!ev || !pr) continue;',
'      activities.push({',
'        id: "interest-" + row.id,',
'        type: row.status,',
'        user_id: row.user_id,',
'        user_name: pr.name,',
'        user_username: pr.username,',
'        created_at: row.created_at,',
'        event_id: row.event_id,',
'        event_title: ev.title,',
'        event_date: ev.start_date,',
'        event_image: ev.hero_image,',
'      });',
'    }',
'',
'    // Review activity',
'    const { data: reviews } = await supabase',
'      .from("event_reviews")',
'      .select("id, user_id, event_id, rating, comment, created_at")',
'      .in("user_id", friendIds)',
'      .order("created_at", { ascending: false })',
'      .limit(30);',
'',
'    for (const r of reviews || []) {',
'      const ev = eventById[r.event_id];',
'      const pr = profileById[r.user_id];',
'      if (!ev || !pr) continue;',
'      activities.push({',
'        id: "review-" + r.id,',
'        type: "review",',
'        user_id: r.user_id,',
'        user_name: pr.name,',
'        user_username: pr.username,',
'        created_at: r.created_at,',
'        event_id: r.event_id,',
'        event_title: ev.title,',
'        event_date: ev.start_date,',
'        event_image: ev.hero_image,',
'        rating: r.rating,',
'        comment: r.comment,',
'      });',
'    }',
'  }',
'',
'  activities.sort((a, b) => (a.created_at < b.created_at ? 1 : -1));',
'  const shown = activities.slice(0, 30);',
'',
'  return (',
'    <div className="max-w-3xl mx-auto px-6 py-12">',
'      <h1',
'        className="text-5xl font-bold uppercase mb-8"',
'        style={{ fontFamily: "var(--font-antonio)" }}',
'      >',
'        Feed',
'      </h1>',
'',
'      {shown.length === 0 ? (',
'        <div className="rounded-2xl border border-gray-200 bg-gray-50 p-12 text-center">',
'          <p className="text-gray-600 mb-4">No activity from your friends yet.</p>',
'          <Link href="/search" className="inline-block px-6 py-3 bg-black text-white rounded-full text-sm font-medium hover:bg-gray-800">',
'            Find events',
'          </Link>',
'        </div>',
'      ) : (',
'        <ul className="space-y-4">',
'          {shown.map((a) => {',
'            const initials = a.user_name.split(" ").map((w) => w[0]).join("").slice(0, 2).toUpperCase();',
'            return (',
'              <li key={a.id} className="rounded-2xl border border-gray-200 overflow-hidden">',
'                <div className="flex items-start gap-4 p-4">',
'                  <Link href={a.user_username ? "/u/" + a.user_username : "#"} className="w-10 h-10 rounded-full bg-black text-white flex items-center justify-center text-sm font-bold flex-shrink-0">',
'                    {initials}',
'                  </Link>',
'                  <div className="flex-1 min-w-0">',
'                    <p className="text-sm">',
'                      <Link href={a.user_username ? "/u/" + a.user_username : "#"} className="font-medium hover:underline">',
'                        {a.user_name}',
'                      </Link>',
'                      {a.type === "going" && <span className="text-gray-600"> is going to </span>}',
'                      {a.type === "interested" && <span className="text-gray-600"> is interested in </span>}',
'                      {a.type === "review" && <span className="text-gray-600"> reviewed </span>}',
'                      {a.event_id && (',
'                        <Link href={"/event/" + a.event_id} className="font-medium hover:underline">',
'                          {a.event_title}',
'                        </Link>',
'                      )}',
'                    </p>',
'                    <p className="text-xs text-gray-500 mt-0.5">{formatDate(a.event_date)}</p>',
'                    {a.type === "review" && a.rating !== undefined && (',
'                      <div className="mt-2">',
'                        <div className="flex items-center gap-1">',
'                          {[1, 2, 3, 4, 5].map((n) => (',
'                            <span key={n} className={n <= (a.rating || 0) ? "text-yellow-500" : "text-gray-300"}>',
'                              ★',
'                            </span>',
'                          ))}',
'                        </div>',
'                        {a.comment && <p className="text-sm text-gray-700 mt-1">{a.comment}</p>}',
'                      </div>',
'                    )}',
'                  </div>',
'                  {a.event_image && (',
'                    <Link href={a.event_id ? "/event/" + a.event_id : "#"} className="flex-shrink-0">',
'                      <img src={a.event_image} alt={a.event_title || ""} className="w-20 h-20 rounded-xl object-cover bg-gray-100" />',
'                    </Link>',
'                  )}',
'                </div>',
'              </li>',
'            );',
'          })}',
'        </ul>',
'      )}',
'    </div>',
'  );',
'}',
].join("\n");
fs.writeFileSync("app/feed/page.tsx", content);
console.log("app/feed/page.tsx written:", content.length, "chars");