const fs = require("fs");
const content = [
'import Link from "next/link";',
'import { createServerSupabase } from "@/lib/supabase/server";',
'import FriendButton from "@/components/FriendButton";',
'',
'export const dynamic = "force-dynamic";',
'',
'type Person = {',
'  id: string;',
'  full_name: string | null;',
'  username: string | null;',
'  city: string | null;',
'  bio: string | null;',
'};',
'',
'export default async function PeoplePage({',
'  searchParams,',
'}: {',
'  searchParams: Promise<{ q?: string }>;',
'}) {',
'  const { q } = await searchParams;',
'  const query = (q || "").trim();',
'',
'  const supabase = await createServerSupabase();',
'  const { data: { user } } = await supabase.auth.getUser();',
'',
'  let profilesQuery = supabase',
'    .from("profiles")',
'    .select("id, full_name, username, city, bio")',
'    .eq("is_public", true)',
'    .not("username", "is", null)',
'    .order("created_at", { ascending: false })',
'    .limit(50);',
'',
'  if (query.length > 0) {',
'    profilesQuery = profilesQuery.or(',
'      "full_name.ilike.%" + query + "%,username.ilike.%" + query + "%"',
'    );',
'  }',
'',
'  const { data: profiles } = await profilesQuery;',
'  let people = (profiles || []) as Person[];',
'',
'  // Exclude self',
'  if (user) {',
'    people = people.filter((p) => p.id !== user.id);',
'  }',
'',
'  // Which of these are already my friends?',
'  let friendIds: string[] = [];',
'  if (user) {',
'    const { data: friendships } = await supabase',
'      .from("friendships")',
'      .select("user_id, friend_id")',
'      .eq("status", "accepted")',
'      .or("user_id.eq." + user.id + ",friend_id.eq." + user.id);',
'    friendIds = (friendships || []).map((f) =>',
'      f.user_id === user.id ? f.friend_id : f.user_id',
'    );',
'  }',
'',
'  return (',
'    <div className="max-w-3xl mx-auto px-6 py-12">',
'      <h1',
'        className="text-5xl font-bold uppercase mb-6"',
'        style={{ fontFamily: "var(--font-antonio)" }}',
'      >',
'        People',
'      </h1>',
'',
'      <form method="get" className="mb-8">',
'        <div className="flex gap-2">',
'          <input',
'            type="text"',
'            name="q"',
'            defaultValue={query}',
'            placeholder="Search by name or @username..."',
'            className="flex-1 px-4 py-3 border border-gray-300 rounded-xl outline-none focus:border-black"',
'          />',
'          <button',
'            type="submit"',
'            className="px-6 py-3 bg-black text-white font-semibold rounded-xl hover:bg-gray-800"',
'          >',
'            Search',
'          </button>',
'        </div>',
'        {query.length > 0 && (',
'          <p className="mt-2 text-sm text-gray-500">',
'            {people.length} {people.length === 1 ? "result" : "results"} for &ldquo;{query}&rdquo;',
'            <Link href="/people" className="ml-3 underline underline-offset-4">',
'              Clear',
'            </Link>',
'          </p>',
'        )}',
'      </form>',
'',
'      {people.length === 0 ? (',
'        <div className="rounded-2xl border border-gray-200 bg-gray-50 p-12 text-center">',
'          <p className="text-gray-600">',
'            {query.length > 0 ? "No one matched your search." : "No public profiles yet."}',
'          </p>',
'        </div>',
'      ) : (',
'        <ul className="divide-y divide-gray-200 border border-gray-200 rounded-2xl">',
'          {people.map((p) => {',
'            const name = p.full_name || p.username || "Someone";',
'            const initials = name.split(" ").map((w) => w[0]).join("").slice(0, 2).toUpperCase();',
'            const isFriend = friendIds.includes(p.id);',
'            return (',
'              <li key={p.id} className="p-4 flex items-center gap-4">',
'                <div className="w-12 h-12 rounded-full bg-black text-white flex items-center justify-center font-bold flex-shrink-0">',
'                  {initials}',
'                </div>',
'                <div className="flex-1 min-w-0">',
'                  <Link',
'                    href={p.username ? "/u/" + p.username : "#"}',
'                    className="font-medium hover:underline"',
'                  >',
'                    {name}',
'                  </Link>',
'                  <p className="text-sm text-gray-500">',
'                    {p.username && "@" + p.username}',
'                    {p.city && (p.username ? " · " + p.city : p.city)}',
'                  </p>',
'                  {p.bio && (',
'                    <p className="text-sm text-gray-600 mt-1 line-clamp-1">{p.bio}</p>',
'                  )}',
'                </div>',
'                {user && (',
'                  <FriendButton',
'                    friendId={p.id}',
'                    initialStatus={isFriend ? "accepted" : null}',
'                  />',
'                )}',
'              </li>',
'            );',
'          })}',
'        </ul>',
'      )}',
'    </div>',
'  );',
'}',
].join("\n");
fs.writeFileSync("app/people/page.tsx", content);
console.log("app/people/page.tsx written:", content.length, "chars");